export const container: string;
export const frame: string;
export const modal: string;
export const modalContent: string;
export const modalDialog: string;
export const modalHeader: string;
export const play: string;
export const thumbnail: string;
export const video: string;
