export { default as App } from './App/App';
export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';
export { default as Layout } from './Layout/Layout';
export { default as Slider } from './Slider/Slider';
export { default as Link } from './Common/Link/Link';
export { default as BlockBase } from './BlockBase/BlockBase';
export { default as VideoBlock } from './VideoBlock/VideoBlock';
export { default as Navigation } from './Navigation/Navigation';
export { default as InstagramFeed } from './InstagramFeed/InstagramFeed';
export { default as ServicesHome } from './Services/ServicesHome/ServicesHome';
export { default as ServicesList } from './Services/ServicesList/ServicesList';
export { PureLanguageSwitcher } from './LanguageSwitcher/LanguageSwitcher';
export { default as LanguageSwitcher } from './LanguageSwitcher/LanguageSwitcher';
export { default as NavigationItem } from './Navigation/NavigationItem/NavigationItem';
export { default as ServicesListItem } from './Services/ServicesList/ServicesListItem/ServicesListItem';
export { default as SpanishFlag } from './Common/Svg/SpanishFlag';
export { default as EnglishFlag } from './Common/Svg/EnglishFlag';
